# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_delete_adminstylestestproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstylestest',
            name='manytomany_e',
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='foreignkey_a',
            field=models.ForeignKey(blank=True, help_text='this is a help text for the foreign key field a', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testapp_adminstylestest_foreignkey_a', to='testapp.AdminStylesTest', verbose_name='ForeignKey A'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='foreignkey_b',
            field=models.ForeignKey(blank=True, help_text='this is a help text for the foreign key field b', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testapp_adminstylestest_foreignkey_b', to='testapp.AdminStylesTest', verbose_name='ForeignKey B'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_a',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field a', related_name='_adminstylestest_manytomany_a_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField A'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_b',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field b', related_name='_adminstylestest_manytomany_b_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField B'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_c',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field c', related_name='_adminstylestest_manytomany_c_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField C'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_d',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field d', related_name='_adminstylestest_manytomany_d_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField D'),
        ),
    ]
