# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-07 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20181030_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleInlineTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boolean', models.BooleanField(default=True, help_text='this is a help text for the boolean field', verbose_name='boolean')),
                ('char', models.CharField(help_text='this is a help text for the char field', max_length=250, verbose_name='charfield')),
                ('char_choices', models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'alkdsjalksdj asdlkj asdlkajs dlakjds lakjdslkajsd l')], help_text='this is a help text for the char field choices', max_length=250, verbose_name='charfield choices')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='this is a help text for the date field', verbose_name='DateField')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.AdminStylesTest')),
            ],
        ),
    ]
