# Generated by Django 3.2.5 on 2021-11-17 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('testapp', '0005_simpleinlinetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstylestest',
            name='filer_file',
            field=filer.fields.file.FilerFileField(help_text='this is a help text for the filer file field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filer_file_set', to='filer.file', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='adminstylestest',
            name='filer_image',
            field=filer.fields.image.FilerImageField(help_text='this is a help text for the filer image field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filer_image_set', to=settings.FILER_IMAGE_MODEL, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='filepath',
            field=models.FilePathField(allow_folders=True, blank=True, default='', help_text='this is a help text for the file path field', path='/home/alaric/Dev/django/django-admin-styles/source/testproject/media', recursive=True, verbose_name='FilePathField'),
        ),
    ]
