# Generated by Django 4.2.1 on 2023-06-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20211117_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstylestest',
            name='foreignkey_a',
            field=models.ForeignKey(blank=True, help_text='this is a help text for the foreign key field a', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_foreignkey_a', to='testapp.adminstylestest', verbose_name='ForeignKey A'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='foreignkey_b',
            field=models.ForeignKey(blank=True, help_text='this is a help text for the foreign key field b', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_foreignkey_b', to='testapp.adminstylestest', verbose_name='ForeignKey B'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_a',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field a', to='testapp.adminstylestest', verbose_name='ManyToManyField A'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_b',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field b', to='testapp.adminstylestest', verbose_name='ManyToManyField B'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_c',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field c', to='testapp.adminstylestest', verbose_name='ManyToManyField C'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_d',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field d', to='testapp.adminstylestest', verbose_name='ManyToManyField D'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='onetoone',
            field=models.OneToOneField(blank=True, help_text='this is a help text for the one to one field', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_onetoone', to='testapp.adminstylestest', verbose_name='OneToOneField'),
        ),
        migrations.AlterField(
            model_name='simpleinlinetest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
