# Generated by Django 3.2.23 on 2023-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_alter_adminstylestest_foreignkey_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_a',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field a', related_name='_testapp_adminstylestest_manytomany_a_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField A'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_b',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field b', related_name='_testapp_adminstylestest_manytomany_b_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField B'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_c',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field c', related_name='_testapp_adminstylestest_manytomany_c_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField C'),
        ),
        migrations.AlterField(
            model_name='adminstylestest',
            name='manytomany_d',
            field=models.ManyToManyField(blank=True, help_text='this is a help text for the many to many field d', related_name='_testapp_adminstylestest_manytomany_d_+', to='testapp.AdminStylesTest', verbose_name='ManyToManyField D'),
        ),
    ]
